events {}

http {

    upstream backend_servers {
        server backend1:3000;
        server backend2:3000;
    }

    # HTTP → HTTPS redirect
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/localhost.pem;
        ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

        location /api/ {
            proxy_pass http://backend_servers/;
        }

        location / {
            return 200 "HTTPS Reverse Proxy Working";
        }
    }
}