services:

  backend1:
    build: ./backend
    container_name: backend1

  backend2:
    build: ./backend
    container_name: backend2

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
