events {}

http {

    upstream backend_servers {
        server backend1:3000;
        server backend2:3000;
    }

    server {
        listen 80;

        location /api {
            proxy_pass http://backend_servers;
        }
    }

}
