events {}

http {

 upstream backend_servers {
   server server:5000;
 }

 server {
   listen 80;
   return 301 https://$host$request_uri;
 }

 server {
   listen 443 ssl;

   ssl_certificate /etc/nginx/certs/localhost.pem;
   ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

   location /api/ {
      proxy_pass http://backend_servers/;
   }

   location / {
      proxy_pass http://client:3000;
   }
 }

}
